// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWEB.Final.Core.Data;

#nullable disable

namespace NWEB.Final.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231214020049_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NWEB.Final.Core.Models.Congdan", b =>
                {
                    b.Property<string>("MaCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCD");

                    b.ToTable("Congdan");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.LieuVacXin", b =>
                {
                    b.Property<string>("MaLieuVX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiVX")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLo")
                        .HasColumnType("int");

                    b.HasKey("MaLieuVX");

                    b.HasIndex("MaLoaiVX");

                    b.ToTable("LieuVacXin");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.LoaiVacXin", b =>
                {
                    b.Property<string>("MaLoaiVX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NuocSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNgayTienNhac")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiVX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiVX");

                    b.ToTable("LoaiVacXin");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.TiemChung", b =>
                {
                    b.Property<string>("MaTC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLieuVX")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDKTienMui2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiemMui1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiemMui2")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTC");

                    b.HasIndex("MaCD");

                    b.HasIndex("MaLieuVX");

                    b.ToTable("TiemChung");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.LieuVacXin", b =>
                {
                    b.HasOne("NWEB.Final.Core.Models.LoaiVacXin", "LoaiVacXins")
                        .WithMany("LieuVacXins")
                        .HasForeignKey("MaLoaiVX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiVacXins");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.TiemChung", b =>
                {
                    b.HasOne("NWEB.Final.Core.Models.Congdan", "Congdans")
                        .WithMany("TiemChungs")
                        .HasForeignKey("MaCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NWEB.Final.Core.Models.LieuVacXin", "LieuVacXins")
                        .WithMany("TiemChungs")
                        .HasForeignKey("MaLieuVX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Congdans");

                    b.Navigation("LieuVacXins");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.Congdan", b =>
                {
                    b.Navigation("TiemChungs");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.LieuVacXin", b =>
                {
                    b.Navigation("TiemChungs");
                });

            modelBuilder.Entity("NWEB.Final.Core.Models.LoaiVacXin", b =>
                {
                    b.Navigation("LieuVacXins");
                });
#pragma warning restore 612, 618
        }
    }
}
